[build]
  publish = "public"
  command = "cd netlify/functions && npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/blog/remettre-son-mari-au-sport"
  to   = "/blog/remettre-son-mari-au-sport.html"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
  force = false
